### ISSUE TITLE
1.7 fix instructions unclear

### ISSUE THREAD

**Issue by aaronperkins** [ShawMerlin/NES-Slotmaster#2]
Love this project but I'm struggling with the 1.7 fix.

The schematic shows pin 15 to 29 but the photos show pin 15 to 27. Which is it? Also are we required to cut a trace? The schematic seems to indicate that, but it's not in the written instructions.

Thanks!

**Comment by ShawMerlin** [comment]
The trace cut is not required as it's connected to a Expansion port pin.

You are correct that the pin I have marked and soldered to in my real life photo's is Pin 27 and wrong.  This should be on the one next to it.  Pin 15 is the IRQ which hardly any of North America NES's.  I will get the photo's updated to show the correct pin.

The critical one is pin 56 on the 72 pin connected to pin 32 on the 64 pin connector.
This is the PPU /WE and is the cause of the garbage artifacts that appear on some of the NES Games.

Thank you for pointing this out and i will get this corrected tonight.  Please follow the schematic and not the real life picture.

Thanks,
-Merlin Shaw

**Comment by ShawMerlin** [comment]
Instructions have been corrected to show Pin 29 in the real photo's and not Pin 27.
Thank you again for finding this and raising the alarm.  :)
