### ISSUE TITLE
Bottom PCB clearance issues with Hi-Def NES using the Laserbear No Cut Kit

### ISSUE THREAD

**Issue by pmgducati** [ShawMerlin/NES-Slotmaster#4]
Hello,
I am working on the DIY (1.8c) version of the slotmaster and have run into a clearance issue.  I have the Hi-DefNES Kit (https://www.game-tech.us/product/hi-def-nes/) and using the Laser Bear No Cut Kit (https://www.laserbear.net/products/nes-front-loader-hi-defnes-no-cut-kit).  The bottom PCB does not have clearance to install with the Hi Def PCB install Location.  I was able to make it fit by trimming your PCB down leaving ~1mm below the 8 Pin header traces.  Would you consider updating the PCB to allow for this?  Im happy to help test fit PCBs.

Here are some picture of the modifications that I had to make to the PCB:
Mounted in the NES:
![PXL_20240507_220554852](https://github.com/ShawMerlin/NES-Slotmaster/assets/20894227/7f16541d-ef3f-4c59-b490-194ff56f7a6b)
![PXL_20240507_220559403](https://github.com/ShawMerlin/NES-Slotmaster/assets/20894227/73065514-b72c-4071-bccd-ffa6939e051e)
Loose:
![PXL_20240507_220636283](https://github.com/ShawMerlin/NES-Slotmaster/assets/20894227/723c96c2-c9df-42b7-8916-ab64cc4618ed)
Measurements:
![PXL_20240507_220654750](https://github.com/ShawMerlin/NES-Slotmaster/assets/20894227/2241d714-d28d-4c6b-ad09-e300fec33dab)

**Comment by ShawMerlin** [comment]
Thank you for the pictures and measurements.  I will make updates to the board so that they will accommodated the Hi-Def Mod.

**Comment by pmgducati** [comment]
Thanks!

**Comment by ShawMerlin** [comment]
How does this look?  If you can send me an email, I will send you the gerbers.  merlin (dot) shaw at google

<img width="731" alt="image" src="https://github.com/ShawMerlin/NES-Slotmaster/assets/70423454/b25643ce-2977-4808-bcae-8daea4b62262">

**Comment by pmgducati** [comment]
Email sent!

**Comment by ShawMerlin** [comment]
Our new boards will have the shorter bottom so this will not be an issue going forward.
Thank you again for bringing this to our attention.
