### ISSUE TITLE
3D Print files are not compatible with PCBWAY

### ISSUE THREAD

**Issue by Tz1rf** [ShawMerlin/NES-Slotmaster#9]
Tried to order the 3D print of the Slotmaster Cartridge Unit on PCBway from the link in the description. You cannot order it as the file type (7z file) is not suitable for 3D Printing. Is there a compatible file type (STP, STEP, STL or OBJ) available?

**Comment by ShawMerlin** [comment]
We have the first rendition still in our GitHub I believe.  That one is a
Stl file.  I will have to see what is going on with that.

Thanks for letting me know.
